### ISSUE TITLE
everytime i insert data into it is showing data at that time but after that when i close and open it that data is deleted can you please help me solving this

### ISSUE THREAD

**Issue by abhishekkuruba** [partha7278/GeneralStore#1]

**Comment by partha7278** [comment]
your inserted data is delete because application run on VS (visual studio).
Everytime when ever you run the application VS create a build and open it.

For proper use, you have to create a build of this application and install it on your computer .

**Comment by abhishekkuruba** [comment]
Thank you so much for responding bro.i will building exe and then get back
to you

**Comment by abhishekkuruba** [comment]
Thank you Now it is working fine
